title: Codingcooker74's Blog
description: 코딩과 개발에 관한 다양한 이야기를 풀어내는 공간입니다.
url: "https://Codingcooker74.github.io"
baseurl: ""

author:
  name: Codingcooker74
  email: your-email@example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - auto_blog.py
  - new_post.bat
  - README.md
  - plans/
